KNOWN_CAREER_PAGES = {

    "OpenAI": "https://openai.com/careers",
    "Anthropic": "https://www.anthropic.com/careers",
    "Databricks": "https://www.databricks.com/company/careers",
    "Scale AI": "https://scale.com/careers",
    "Perplexity": "https://www.perplexity.ai/careers",
    "Google": "https://careers.google.com",
    "Microsoft": "https://careers.microsoft.com",
    "Amazon": "https://www.amazon.jobs",
    "Meta": "https://www.metacareers.com",
    "NVIDIA": "https://www.nvidia.com/en-us/about-nvidia/careers",
    "Goldman Sachs": "https://higher.gs.com",
    "JPMorgan Chase": "https://careers.jpmorgan.com",
    "Morgan Stanley": "https://www.morganstanley.com/careers",
    "Citadel": "https://www.citadel.com/careers",
    "Jane Street": "https://www.janestreet.com/join-jane-street",
    "Two Sigma": "https://www.twosigma.com/careers",

    "OpenAI": "https://openai.com/careers",
    "Anthropic": "https://www.anthropic.com/careers",
    "Databricks": "https://www.databricks.com/company/careers",
    "DataBricks": "https://www.databricks.com/company/careers",
    "Scale AI": "https://scale.com/careers",
    "Perplexity": "https://www.perplexity.ai/careers",
    "Cohere": "https://cohere.com/careers",
    "Mistral AI": "https://mistral.ai/careers",
    "Hugging Face": "https://huggingface.co/jobs",
    "Palantir": "https://www.palantir.com/careers",

    "Google": "https://careers.google.com",
    "Microsoft": "https://careers.microsoft.com",
    "Amazon": "https://www.amazon.jobs",
    "Meta": "https://www.metacareers.com",
    "Facebook": "https://www.metacareers.com",
    "Apple": "https://jobs.apple.com",
    "NVIDIA": "https://www.nvidia.com/en-us/about-nvidia/careers",
    "Adobe": "https://careers.adobe.com",
    "Salesforce": "https://careers.salesforce.com",
    "Oracle": "https://careers.oracle.com",
    "IBM": "https://www.ibm.com/careers",
    "Cisco": "https://jobs.cisco.com",
    "Dell": "https://jobs.dell.com",
    "VMware": "https://careers.vmware.com",

    "Cursor": "https://cursor.com/careers",
    "ElevenLabs": "https://elevenlabs.io/careers",
    "Runway": "https://runwayml.com/careers",
    "Glean": "https://www.glean.com/careers",
    "Adept": "https://www.adept.ai/careers",
    "Harvey": "https://www.harvey.ai/careers",
    "Sierra": "https://sierra.ai/careers",
    "Together AI": "https://www.together.ai/careers",
    "Writer": "https://writer.com/careers",
    "Pinecone": "https://www.pinecone.io/careers",
    "Weights & Biases": "https://wandb.ai/site/careers",
    "OctoAI": "https://octo.ai/careers",
    "Replit": "https://replit.com/careers",

    # FinTech Startups

    "Mercury": "https://mercury.com/jobs",
    "Alpaca": "https://alpaca.markets/careers",
    "Wise": "https://wise.jobs",
    "Airwallex": "https://careers.airwallex.com",
    "Flutterwave": "https://flutterwave.com/careers",
    "Chime": "https://careers.chime.com",
    "Nubank": "https://building.nubank.com/careers",
    "Ramp": "https://ramp.com/careers",
    "Brex": "https://www.brex.com/careers",

    # Quant / Trading Firms

    "Jump Trading": "https://www.jumptrading.com/careers",
    "Five Rings": "https://fiverings.com/careers",
    "Akuna Capital": "https://akunacapital.com/careers",
    "Flow Traders": "https://www.flowtraders.com/careers",
    "SIG": "https://careers.sig.com",
    "Belvedere Trading": "https://www.belvederetrading.com/careers",

    # AI Infrastructure

    "Modal": "https://modal.com/careers",
    "Anyscale": "https://www.anyscale.com/careers",
    "MotherDuck": "https://motherduck.com/careers",
    "Neon": "https://neon.tech/careers",
    "Supabase": "https://supabase.com/careers",
    "Vercel": "https://vercel.com/careers",

    # Indian Startups

    "Meesho": "https://careers.meesho.com",
    "Zepto": "https://careers.zeptonow.com",
    "CRED": "https://careers.cred.club",
    "Groww": "https://groww.in/careers",
    "Jar": "https://www.jar.app/careers",
    "Fi Money": "https://fi.money/careers",
    "Navi": "https://navi.com/careers",
    "Juspay": "https://juspay.io/careers",
    "Postman": "https://www.postman.com/company/careers",
    "BrowserStack": "https://www.browserstack.com/careers",

    "Stripe": "https://stripe.com/jobs",
    "PayPal": "https://careers.pypl.com",
    "Visa": "https://corporate.visa.com/en/careers.html",
    "Mastercard": "https://careers.mastercard.com",
    "American Express": "https://www.americanexpress.com/en-us/careers",
    "Robinhood": "https://careers.robinhood.com",
    "Coinbase": "https://www.coinbase.com/careers",
    "Plaid": "https://plaid.com/careers",
    "Brex": "https://www.brex.com/careers",
    "Ramp": "https://ramp.com/careers",

    "Razorpay": "https://razorpay.com/jobs",
    "PhonePe": "https://www.phonepe.com/careers",
    "Groww": "https://groww.in/careers",
    "Zerodha": "https://zerodha.com/careers",
    "CRED": "https://careers.cred.club",

    "JPMorgan Chase": "https://careers.jpmorgan.com",
    "Goldman Sachs": "https://higher.gs.com",
    "Morgan Stanley": "https://www.morganstanley.com/careers",
    "Bank of America": "https://careers.bankofamerica.com",
    "Citi": "https://jobs.citi.com",
    "Citigroup": "https://jobs.citi.com",
    "Barclays": "https://search.jobs.barclays",
    "HSBC": "https://www.hsbc.com/careers",
    "UBS": "https://www.ubs.com/global/en/careers.html",
    "Deutsche Bank": "https://careers.db.com",

    "Citadel": "https://www.citadel.com/careers",
    "Jane Street": "https://www.janestreet.com/join-jane-street",
    "Two Sigma": "https://www.twosigma.com/careers",
    "D.E. Shaw": "https://www.deshaw.com/careers",
    "Hudson River Trading": "https://www.hudsonrivertrading.com/careers",
    "IMC Trading": "https://careers.imc.com",
    "Optiver": "https://optiver.com/working-at-optiver",
    "WorldQuant": "https://www.worldquant.com/careers",
    "Tower Research": "https://www.tower-research.com/careers",
    "DRW": "https://drw.com/work-at-drw",

    "Snowflake": "https://careers.snowflake.com",
    "Datadog": "https://careers.datadoghq.com",
    "HashiCorp": "https://www.hashicorp.com/careers",
    "MongoDB": "https://www.mongodb.com/careers",
    "Confluent": "https://www.confluent.io/careers",
    "DataRobot": "https://www.datarobot.com/careers",

    "Accenture": "https://www.accenture.com/careers",
    "Deloitte": "https://www2.deloitte.com/careers",
    "KPMG": "https://kpmg.com/careers",
    "Ernst & Young": "https://careers.ey.com",
    "PwC": "https://www.pwc.com/careers",
    "McKinsey": "https://www.mckinsey.com/careers",
    "Boston Consulting Group": "https://careers.bcg.com",
    "Bain & Company": "https://www.bain.com/careers",

    "Cohere": "https://cohere.com/careers",
    "Mistral AI": "https://mistral.ai/careers",
    "Hugging Face": "https://huggingface.co/jobs",
    "Perplexity": "https://www.perplexity.ai/careers",
    "Scale AI": "https://scale.com/careers",

    "Stripe": "https://stripe.com/jobs",
    "Plaid": "https://plaid.com/careers",
    "Brex": "https://www.brex.com/careers",
    "Ramp": "https://ramp.com/careers",
    "Robinhood": "https://careers.robinhood.com",
    "Coinbase": "https://www.coinbase.com/careers",
    "PayPal": "https://careers.pypl.com",
    "Visa": "https://corporate.visa.com/en/careers.html",
    "Mastercard": "https://careers.mastercard.com",
    "American Express": "https://www.americanexpress.com/en-us/careers",

    "Hudson River Trading": "https://www.hudsonrivertrading.com/careers",
    "IMC Trading": "https://careers.imc.com",
    "Optiver": "https://optiver.com/working-at-optiver",
    "WorldQuant": "https://www.worldquant.com/careers",
    "Tower Research": "https://www.tower-research.com/careers",
    "DRW": "https://drw.com/work-at-drw",

    "Snowflake": "https://careers.snowflake.com",
    "Datadog": "https://careers.datadoghq.com",
    "HashiCorp": "https://www.hashicorp.com/careers",
    "MongoDB": "https://www.mongodb.com/careers",
    "Confluent": "https://www.confluent.io/careers",

    "Razorpay": "https://razorpay.com/jobs",
    "PhonePe": "https://www.phonepe.com/careers",
    "Groww": "https://groww.in/careers",
    "Zerodha": "https://zerodha.com/careers",
    "CRED": "https://careers.cred.club",

    "Citi": "https://jobs.citi.com",
    "Barclays": "https://search.jobs.barclays",
    "HSBC": "https://www.hsbc.com/careers",
    "UBS": "https://www.ubs.com/global/en/careers.html",
    "Bank of America": "https://careers.bankofamerica.com"

}